class Autogenerated {
  String studentId;
  String studentName;
  String studentScores;

  Autogenerated({this.studentId, this.studentName, this.studentScores});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    studentId = json['studentId'];
    studentName = json['studentName'];
    studentScores = json['studentScores'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['studentId'] = this.studentId;
    data['studentName'] = this.studentName;
    data['studentScores'] = this.studentScores;
    return data;
  }
}