name: weapp_6_firebase
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.1.0
  firebase_database: ^4.0.0
  firebase_analytics:
  firebase_crashlytics:
  google_sign_in:
  email_auth: ^0.0.1+2
  intl:
  image_picker: ^0.6.6+1
  transparent_image: ^1.0.0
  carousel_slider: ^2.3.1
  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.24.1
  path_provider:
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  flutter_webview_plugin:
  simple_auth: ^2.0.5
  simple_auth_flutter: ^2.0.4
  dio:
  folder_file_saver: ^1.0.0+2
  percent_indicator: ^2.1.1+1
  permission_handler:
  share: ^0.6.5+4
  flutter_share_me: ^0.9.2
  shimmer: ^1.1.2
  shared_preferences: ^0.5.12+4
  flutter_inapp_purchase: ^3.0.1
  font_awesome_flutter: ^8.11.0
  json_annotation: ^3.1.1
  overlay_support: ^1.0.5
  esys_flutter_share:
  photo_view: ^0.10.3
  url_launcher: ^5.7.10
  email_launcher: ^1.0.0
  flutter_sms: ^2.1.1
  platform_action_sheet: ^0.0.3
  popover: ^0.0.5
#  social_share:
  screenshot: ^0.1.1
  provider: ^4.3.3
#  chewie_audio: ^1.1.1
  video_player:
  audioplayers:
#  chewie:
#  location: ^3.0.2
  stripe_payment:
  flutter_phone_direct_caller: ^1.0.1
  sms: ^0.2.0
  audio_manager: ^0.7.3
  video_viewer: ^1.0.9
  sqflite: ^1.3.2+2
  add_2_calendar: ^1.3.0
  device_calendar:
  cached_network_image:
  popup_menu: ^1.0.5
  progress_dialog:


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/music/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
